### ISSUE TITLE
Esperanto letters not displaying well

### ISSUE THREAD

**Issue by behilam** [Orelo-Software/orelo-blog-nextjs#4]
![image](https://user-images.githubusercontent.com/73665457/181863408-5e5405d2-8ce0-4242-b88f-9418982ffc4c.png)

The Esperanto letters with "ĉapelo" (e.g. ĉĝĵĥŝŭ) are not included in the font we currently use

**Comment by behilam** [comment]
Here are 3 options I found that are similar to Avenir and support esperanto characters. Which one do you like?

<details><summary>Comparison</summary>

| <h2>Avenir (original)</h2> ![image](https://user-images.githubusercontent.com/73665457/182481792-1bf171c8-f687-42ae-b230-d41ddd4a99f8.png) | <h2>Montserrat</h2> ![image](https://user-images.githubusercontent.com/73665457/182482466-884f8139-c02d-429c-8d90-fd1a4b717321.png) |
| ------- | ------------ |
| <h2>Sarabun</h2> ![image](https://user-images.githubusercontent.com/73665457/182481682-e1be5fad-a899-48c8-a77a-c980924d3f8c.png) | <h2>Roboto</h2> ![image](https://user-images.githubusercontent.com/73665457/182482129-7504f59e-7f58-433e-ac24-d46c116e0429.png) |

</details>

**Comment by Velua** [comment]
Montserrat :partying_face: :fire:

**Comment by Velua** [comment]
Can this be closed now? @behilam
