### ISSUE TITLE
Localization for cards that have typescript data inside

### ISSUE THREAD

**Issue by behilam** [Orelo-Software/orelo-blog-nextjs#5]
The localizer ([react-i18next](https://react.i18next.com/)) uses json files to get the localized strings, and it works well (I included type annotation exports for them too), but for each of the team members there is also information about social media, and for that I used an enum with each of the social media:

| Declaration | Usage Example |
|-|-|
| ![image](https://user-images.githubusercontent.com/73665457/182217007-b3d7efdc-41e0-4631-b1b6-4d0e45fc83fc.png) | ![image](https://user-images.githubusercontent.com/73665457/182217216-910e1be9-8d70-43d2-9bb5-c888fb10066b.png) |

The enum facilitates the programatic generation of the social icons and also prevents from any use of not defined social media components, so if it is possible I would like to keep using it.

- So one solution would be to keep the localizable strings (json files) (e.g. name, position) and the social media data (ts files) in separate files, but that would give problems when synchronizing the data between those files, so not at all good in my opinion.

- Other solution would be to somehow enable react-i18next to read/make use of the ts data files, which would be optimal, but I still have to check if there is a native way to achieve that.

- Or, if no other solution is found, we would need to remove the enum and work without its advantages, which is practical, because content about it won't change much, but, understandably, not ideal.

**Comment by behilam** [comment]
618847f14a02c7a16d62c0b5fa5b6a6ab88a17f0 makes use of the original ts file as main data file, and uses the name of each team member as key to get the localized information from the json files. Although it requires a little bit more of synchronization between files, this implementation conserves the previous code with minimal changes

**Comment by Velua** [comment]
We'll discuss this one in our next meeting, I'm failing to see what needs to be translated here.

**Comment by behilam** [comment]
Solution accepted and refactor applied, as advised by Velua. Thank you
