### ISSUE TITLE
Esperanto flag/star for esperanto speakers in the team

### ISSUE THREAD

**Issue by behilam** [Orelo-Software/orelo-blog-nextjs#9]
Here are some options, using a star and using the flag. Which one do you prefer?

![image](https://user-images.githubusercontent.com/73665457/182731565-80680c69-3f6e-41be-b382-fe34a76811b0.png)
![image](https://user-images.githubusercontent.com/73665457/182731621-b0a4dd95-24fc-433e-96e0-a3f3c0f128c9.png)

**Comment by Velua** [comment]
I can't tell hey... lets make it text-right on the same line as the name. 

Ask Luis what he thinks

**Comment by behilam** [comment]
Opened PR #16  for this issue. Further discussion will continue there
